export { registerInitCommand } from './commands/init';
export { registerDeployCommand } from './commands/deploy';
export { registerStatusCommand } from './commands/status';
export { registerStartCommand } from './commands/start';
export { registerStopCommand } from './commands/stop';
export { registerLogsCommand } from './commands/logs';
export { registerAuditCommand } from './commands/audit';
export { registerDoctorCommand } from './commands/doctor';
export { registerConsensusCommand } from './commands/consensus';
export { ROLES, type RoleName, type RoleConfig, type TemplateVars } from './lib/roles';
export { substitute } from './lib/template';
export { generateAgentFiles } from './lib/generator';
export { checkConsensus, buildConfigFromEnv } from './lib/consensus';
export { executeTx, verifyCastCall } from './lib/tx-executor';